version: 0.0
os: linux
files:
    - source: /
      destination: /home/ubuntu/express
hooks:
    Install:
        - location: scripts/install_dependencies.sh
          timeout: 120
          runas: ubuntu
    ApplicationStart:
        - location: scripts/start_server.sh
          timeout: 120
          runas: ubuntu
    ApplicationStop:
        - location: scripts/stop_server.sh
          timeout: 120
          runas: ubuntu
